/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as oracle from "./oracle";
export type { oracle };
import type * as test from "./test";
export type { test };
import type * as vault from "./vault";
export type { vault };
