version = 1

[[annotations]]
path = [
    ".gas-snapshot",
    ".github/workflows/**/",
    ".gitignore",
    ".gitmodules",
    ".idea/**/",
    ".prettierignore",
    ".prettierrc.yaml",
    ".solhint.json",
    "CONTRIBUTING.md",
    "README.md",
    "erc1155Metadata/**/",
    "flake.lock",
    "flake.nix",
    "foundry.toml",
    "slither.config.json",
    "REUSE.toml"
]
SPDX-FileCopyrightText = "Copyright (c) 2020 thedavidmeister"
SPDX-License-Identifier = "LicenseRef-DCL-1.0"
