/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITierV2,
  ITierV2Interface,
} from "../../../../../@beehiveinnovation/rain-protocol/contracts/tier/ITierV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "context",
        type: "uint256[]",
      },
    ],
    name: "report",
    outputs: [
      {
        internalType: "uint256",
        name: "report",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tier",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "context",
        type: "uint256[]",
      },
    ],
    name: "reportTimeForTier",
    outputs: [
      {
        internalType: "uint256",
        name: "time",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ITierV2__factory {
  static readonly abi = _abi;
  static createInterface(): ITierV2Interface {
    return new utils.Interface(_abi) as ITierV2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITierV2 {
    return new Contract(address, _abi, signerOrProvider) as ITierV2;
  }
}
