/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestChainlinkDataFeed } from "./TestChainlinkDataFeed";
export type { TestErc20 } from "./TestErc20";
export type { TestPriceOracle } from "./TestPriceOracle";
