/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IReceipt } from "./IReceipt";
export type { IReceiptOwner } from "./IReceiptOwner";
export type { Receipt } from "./Receipt";
export type { ReceiptFactory } from "./ReceiptFactory";
export type { ReceiptVault } from "./ReceiptVault";
