/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20PriceOracleReceiptVault } from "./ERC20PriceOracleReceiptVault";
export type { ERC20PriceOracleReceiptVaultFactory } from "./ERC20PriceOracleReceiptVaultFactory";
