/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IReceiptOwner,
  IReceiptOwnerInterface,
} from "../../../../contracts/vault/receipt/IReceiptOwner";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "authorizeReceiptInformation",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "authorizeReceiptTransfer",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IReceiptOwner__factory {
  static readonly abi = _abi;
  static createInterface(): IReceiptOwnerInterface {
    return new utils.Interface(_abi) as IReceiptOwnerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IReceiptOwner {
    return new Contract(address, _abi, signerOrProvider) as IReceiptOwner;
  }
}
