/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as offchainAsset from "./offchainAsset";
export type { offchainAsset };
import type * as priceOracle from "./priceOracle";
export type { priceOracle };
import type * as receipt from "./receipt";
export type { receipt };
