/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export type VaultConfigStruct = {
  asset: PromiseOrValue<string>;
  name: PromiseOrValue<string>;
  symbol: PromiseOrValue<string>;
};

export type VaultConfigStructOutput = [string, string, string] & {
  asset: string;
  name: string;
  symbol: string;
};

export type ReceiptVaultConfigStruct = {
  receipt: PromiseOrValue<string>;
  vaultConfig: VaultConfigStruct;
};

export type ReceiptVaultConfigStructOutput = [
  string,
  VaultConfigStructOutput
] & { receipt: string; vaultConfig: VaultConfigStructOutput };

export type OffchainAssetReceiptVaultConfigStruct = {
  admin: PromiseOrValue<string>;
  receiptVaultConfig: ReceiptVaultConfigStruct;
};

export type OffchainAssetReceiptVaultConfigStructOutput = [
  string,
  ReceiptVaultConfigStructOutput
] & { admin: string; receiptVaultConfig: ReceiptVaultConfigStructOutput };

export interface OffchainAssetReceiptVaultInterface extends utils.Interface {
  functions: {
    "CERTIFIER()": FunctionFragment;
    "CERTIFIER_ADMIN()": FunctionFragment;
    "CONFISCATOR()": FunctionFragment;
    "CONFISCATOR_ADMIN()": FunctionFragment;
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "DEPOSITOR()": FunctionFragment;
    "DEPOSITOR_ADMIN()": FunctionFragment;
    "ERC1155TIERER()": FunctionFragment;
    "ERC1155TIERER_ADMIN()": FunctionFragment;
    "ERC20SNAPSHOTTER()": FunctionFragment;
    "ERC20SNAPSHOTTER_ADMIN()": FunctionFragment;
    "ERC20TIERER()": FunctionFragment;
    "ERC20TIERER_ADMIN()": FunctionFragment;
    "HANDLER()": FunctionFragment;
    "HANDLER_ADMIN()": FunctionFragment;
    "WITHDRAWER()": FunctionFragment;
    "WITHDRAWER_ADMIN()": FunctionFragment;
    "allowance(address,address)": FunctionFragment;
    "approve(address,uint256)": FunctionFragment;
    "asset()": FunctionFragment;
    "authorizeReceiptInformation(address,uint256,bytes)": FunctionFragment;
    "authorizeReceiptTransfer(address,address)": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "balanceOfAt(address,uint256)": FunctionFragment;
    "certify(uint32,bytes,bool)": FunctionFragment;
    "confiscateReceipt(address,uint256)": FunctionFragment;
    "confiscateShares(address)": FunctionFragment;
    "convertToAssets(uint256)": FunctionFragment;
    "convertToShares(uint256)": FunctionFragment;
    "decimals()": FunctionFragment;
    "decreaseAllowance(address,uint256)": FunctionFragment;
    "deposit(uint256,address,uint256,bytes)": FunctionFragment;
    "deposit(uint256,address)": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "increaseAllowance(address,uint256)": FunctionFragment;
    "initialize((address,(address,(address,string,string))))": FunctionFragment;
    "maxDeposit(address)": FunctionFragment;
    "maxMint(address)": FunctionFragment;
    "maxRedeem(address,uint256)": FunctionFragment;
    "maxRedeem(address)": FunctionFragment;
    "maxWithdraw(address,uint256)": FunctionFragment;
    "maxWithdraw(address)": FunctionFragment;
    "minShareRatios(address)": FunctionFragment;
    "mint(uint256,address)": FunctionFragment;
    "mint(uint256,address,uint256,bytes)": FunctionFragment;
    "multicall(bytes[])": FunctionFragment;
    "name()": FunctionFragment;
    "previewDeposit(uint256)": FunctionFragment;
    "previewMint(uint256)": FunctionFragment;
    "previewRedeem(uint256)": FunctionFragment;
    "previewRedeem(uint256,uint256)": FunctionFragment;
    "previewWithdraw(uint256)": FunctionFragment;
    "previewWithdraw(uint256,uint256)": FunctionFragment;
    "redeem(uint256,address,address,uint256)": FunctionFragment;
    "redeem(uint256,address,address)": FunctionFragment;
    "redeposit(uint256,address,uint256,bytes)": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "setERC1155Tier(address,uint8,uint256[])": FunctionFragment;
    "setERC20Tier(address,uint8,uint256[])": FunctionFragment;
    "setMinShareRatio(uint256)": FunctionFragment;
    "setWithdrawId(uint256)": FunctionFragment;
    "snapshot()": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "symbol()": FunctionFragment;
    "totalAssets()": FunctionFragment;
    "totalSupply()": FunctionFragment;
    "totalSupplyAt(uint256)": FunctionFragment;
    "transfer(address,uint256)": FunctionFragment;
    "transferFrom(address,address,uint256)": FunctionFragment;
    "withdraw(uint256,address,address,uint256)": FunctionFragment;
    "withdraw(uint256,address,address)": FunctionFragment;
    "withdrawIds(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "CERTIFIER"
      | "CERTIFIER_ADMIN"
      | "CONFISCATOR"
      | "CONFISCATOR_ADMIN"
      | "DEFAULT_ADMIN_ROLE"
      | "DEPOSITOR"
      | "DEPOSITOR_ADMIN"
      | "ERC1155TIERER"
      | "ERC1155TIERER_ADMIN"
      | "ERC20SNAPSHOTTER"
      | "ERC20SNAPSHOTTER_ADMIN"
      | "ERC20TIERER"
      | "ERC20TIERER_ADMIN"
      | "HANDLER"
      | "HANDLER_ADMIN"
      | "WITHDRAWER"
      | "WITHDRAWER_ADMIN"
      | "allowance"
      | "approve"
      | "asset"
      | "authorizeReceiptInformation"
      | "authorizeReceiptTransfer"
      | "balanceOf"
      | "balanceOfAt"
      | "certify"
      | "confiscateReceipt"
      | "confiscateShares"
      | "convertToAssets"
      | "convertToShares"
      | "decimals"
      | "decreaseAllowance"
      | "deposit(uint256,address,uint256,bytes)"
      | "deposit(uint256,address)"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "increaseAllowance"
      | "initialize"
      | "maxDeposit"
      | "maxMint"
      | "maxRedeem(address,uint256)"
      | "maxRedeem(address)"
      | "maxWithdraw(address,uint256)"
      | "maxWithdraw(address)"
      | "minShareRatios"
      | "mint(uint256,address)"
      | "mint(uint256,address,uint256,bytes)"
      | "multicall"
      | "name"
      | "previewDeposit"
      | "previewMint"
      | "previewRedeem(uint256)"
      | "previewRedeem(uint256,uint256)"
      | "previewWithdraw(uint256)"
      | "previewWithdraw(uint256,uint256)"
      | "redeem(uint256,address,address,uint256)"
      | "redeem(uint256,address,address)"
      | "redeposit"
      | "renounceRole"
      | "revokeRole"
      | "setERC1155Tier"
      | "setERC20Tier"
      | "setMinShareRatio"
      | "setWithdrawId"
      | "snapshot"
      | "supportsInterface"
      | "symbol"
      | "totalAssets"
      | "totalSupply"
      | "totalSupplyAt"
      | "transfer"
      | "transferFrom"
      | "withdraw(uint256,address,address,uint256)"
      | "withdraw(uint256,address,address)"
      | "withdrawIds"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "CERTIFIER", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "CERTIFIER_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CONFISCATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CONFISCATOR_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "DEPOSITOR", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "DEPOSITOR_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ERC1155TIERER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ERC1155TIERER_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ERC20SNAPSHOTTER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ERC20SNAPSHOTTER_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ERC20TIERER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ERC20TIERER_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "HANDLER", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "HANDLER_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WITHDRAWER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WITHDRAWER_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "asset", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "authorizeReceiptInformation",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeReceiptTransfer",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfAt",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "certify",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "confiscateReceipt",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "confiscateShares",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "convertToAssets",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "convertToShares",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "decreaseAllowance",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit(uint256,address,uint256,bytes)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit(uint256,address)",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseAllowance",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [OffchainAssetReceiptVaultConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "maxDeposit",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "maxMint",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "maxRedeem(address,uint256)",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "maxRedeem(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "maxWithdraw(address,uint256)",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "maxWithdraw(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "minShareRatios",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "mint(uint256,address)",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "mint(uint256,address,uint256,bytes)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "multicall",
    values: [PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "previewDeposit",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "previewMint",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "previewRedeem(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "previewRedeem(uint256,uint256)",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "previewWithdraw(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "previewWithdraw(uint256,uint256)",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "redeem(uint256,address,address,uint256)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "redeem(uint256,address,address)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "redeposit",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setERC1155Tier",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setERC20Tier",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinShareRatio",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setWithdrawId",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "snapshot", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupplyAt",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw(uint256,address,address,uint256)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw(uint256,address,address)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawIds",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "CERTIFIER", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "CERTIFIER_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CONFISCATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CONFISCATOR_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "DEPOSITOR", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEPOSITOR_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERC1155TIERER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERC1155TIERER_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERC20SNAPSHOTTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERC20SNAPSHOTTER_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERC20TIERER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERC20TIERER_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "HANDLER", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "HANDLER_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "WITHDRAWER", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "WITHDRAWER_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "asset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizeReceiptInformation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeReceiptTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "certify", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confiscateReceipt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confiscateShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertToAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertToShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decreaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deposit(uint256,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deposit(uint256,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "increaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxDeposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxRedeem(address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxRedeem(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxWithdraw(address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxWithdraw(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minShareRatios",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mint(uint256,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mint(uint256,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "multicall", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "previewDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewRedeem(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewRedeem(uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewWithdraw(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewWithdraw(uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeem(uint256,address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeem(uint256,address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "redeposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setERC1155Tier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setERC20Tier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinShareRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWithdrawId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "snapshot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupplyAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdraw(uint256,address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdraw(uint256,address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawIds",
    data: BytesLike
  ): Result;

  events: {
    "Approval(address,address,uint256)": EventFragment;
    "Certify(address,uint256,bytes)": EventFragment;
    "ConfiscateReceipt(address,address,uint256,uint256)": EventFragment;
    "ConfiscateShares(address,address,uint256)": EventFragment;
    "Deposit(address,address,uint256,uint256)": EventFragment;
    "DepositWithReceipt(address,address,uint256,uint256,uint256,bytes)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "OffchainAssetVaultInitialized(address,tuple)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "SetERC1155Tier(address,address,uint256,uint256[])": EventFragment;
    "SetERC20Tier(address,address,uint256,uint256[])": EventFragment;
    "Snapshot(uint256)": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
    "Withdraw(address,address,address,uint256,uint256)": EventFragment;
    "WithdrawWithReceipt(address,address,address,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Certify"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ConfiscateReceipt"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ConfiscateShares"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DepositWithReceipt"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "OffchainAssetVaultInitialized"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetERC1155Tier"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetERC20Tier"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Snapshot"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdraw"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawWithReceipt"): EventFragment;
}

export interface ApprovalEventObject {
  owner: string;
  spender: string;
  value: BigNumber;
}
export type ApprovalEvent = TypedEvent<
  [string, string, BigNumber],
  ApprovalEventObject
>;

export type ApprovalEventFilter = TypedEventFilter<ApprovalEvent>;

export interface CertifyEventObject {
  caller: string;
  until: BigNumber;
  data: string;
}
export type CertifyEvent = TypedEvent<
  [string, BigNumber, string],
  CertifyEventObject
>;

export type CertifyEventFilter = TypedEventFilter<CertifyEvent>;

export interface ConfiscateReceiptEventObject {
  caller: string;
  confiscatee: string;
  id: BigNumber;
  confiscated: BigNumber;
}
export type ConfiscateReceiptEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  ConfiscateReceiptEventObject
>;

export type ConfiscateReceiptEventFilter =
  TypedEventFilter<ConfiscateReceiptEvent>;

export interface ConfiscateSharesEventObject {
  caller: string;
  confiscatee: string;
  confiscated: BigNumber;
}
export type ConfiscateSharesEvent = TypedEvent<
  [string, string, BigNumber],
  ConfiscateSharesEventObject
>;

export type ConfiscateSharesEventFilter =
  TypedEventFilter<ConfiscateSharesEvent>;

export interface DepositEventObject {
  sender: string;
  owner: string;
  assets: BigNumber;
  shares: BigNumber;
}
export type DepositEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  DepositEventObject
>;

export type DepositEventFilter = TypedEventFilter<DepositEvent>;

export interface DepositWithReceiptEventObject {
  sender: string;
  owner: string;
  assets: BigNumber;
  shares: BigNumber;
  id: BigNumber;
  receiptInformation: string;
}
export type DepositWithReceiptEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber, string],
  DepositWithReceiptEventObject
>;

export type DepositWithReceiptEventFilter =
  TypedEventFilter<DepositWithReceiptEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface OffchainAssetVaultInitializedEventObject {
  caller: string;
  config: OffchainAssetReceiptVaultConfigStructOutput;
}
export type OffchainAssetVaultInitializedEvent = TypedEvent<
  [string, OffchainAssetReceiptVaultConfigStructOutput],
  OffchainAssetVaultInitializedEventObject
>;

export type OffchainAssetVaultInitializedEventFilter =
  TypedEventFilter<OffchainAssetVaultInitializedEvent>;

export interface RoleAdminChangedEventObject {
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
}
export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  RoleAdminChangedEventObject
>;

export type RoleAdminChangedEventFilter =
  TypedEventFilter<RoleAdminChangedEvent>;

export interface RoleGrantedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleGrantedEvent = TypedEvent<
  [string, string, string],
  RoleGrantedEventObject
>;

export type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>;

export interface RoleRevokedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleRevokedEvent = TypedEvent<
  [string, string, string],
  RoleRevokedEventObject
>;

export type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>;

export interface SetERC1155TierEventObject {
  caller: string;
  tier: string;
  minimumTier: BigNumber;
  context: BigNumber[];
}
export type SetERC1155TierEvent = TypedEvent<
  [string, string, BigNumber, BigNumber[]],
  SetERC1155TierEventObject
>;

export type SetERC1155TierEventFilter = TypedEventFilter<SetERC1155TierEvent>;

export interface SetERC20TierEventObject {
  caller: string;
  tier: string;
  minimumTier: BigNumber;
  context: BigNumber[];
}
export type SetERC20TierEvent = TypedEvent<
  [string, string, BigNumber, BigNumber[]],
  SetERC20TierEventObject
>;

export type SetERC20TierEventFilter = TypedEventFilter<SetERC20TierEvent>;

export interface SnapshotEventObject {
  id: BigNumber;
}
export type SnapshotEvent = TypedEvent<[BigNumber], SnapshotEventObject>;

export type SnapshotEventFilter = TypedEventFilter<SnapshotEvent>;

export interface TransferEventObject {
  from: string;
  to: string;
  value: BigNumber;
}
export type TransferEvent = TypedEvent<
  [string, string, BigNumber],
  TransferEventObject
>;

export type TransferEventFilter = TypedEventFilter<TransferEvent>;

export interface WithdrawEventObject {
  sender: string;
  receiver: string;
  owner: string;
  assets: BigNumber;
  shares: BigNumber;
}
export type WithdrawEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  WithdrawEventObject
>;

export type WithdrawEventFilter = TypedEventFilter<WithdrawEvent>;

export interface WithdrawWithReceiptEventObject {
  sender: string;
  receiver: string;
  owner: string;
  assets: BigNumber;
  shares: BigNumber;
  id: BigNumber;
}
export type WithdrawWithReceiptEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber, BigNumber],
  WithdrawWithReceiptEventObject
>;

export type WithdrawWithReceiptEventFilter =
  TypedEventFilter<WithdrawWithReceiptEvent>;

export interface OffchainAssetReceiptVault extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OffchainAssetReceiptVaultInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    CERTIFIER(overrides?: CallOverrides): Promise<[string]>;

    CERTIFIER_ADMIN(overrides?: CallOverrides): Promise<[string]>;

    CONFISCATOR(overrides?: CallOverrides): Promise<[string]>;

    CONFISCATOR_ADMIN(overrides?: CallOverrides): Promise<[string]>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    DEPOSITOR(overrides?: CallOverrides): Promise<[string]>;

    DEPOSITOR_ADMIN(overrides?: CallOverrides): Promise<[string]>;

    ERC1155TIERER(overrides?: CallOverrides): Promise<[string]>;

    ERC1155TIERER_ADMIN(overrides?: CallOverrides): Promise<[string]>;

    ERC20SNAPSHOTTER(overrides?: CallOverrides): Promise<[string]>;

    ERC20SNAPSHOTTER_ADMIN(overrides?: CallOverrides): Promise<[string]>;

    ERC20TIERER(overrides?: CallOverrides): Promise<[string]>;

    ERC20TIERER_ADMIN(overrides?: CallOverrides): Promise<[string]>;

    HANDLER(overrides?: CallOverrides): Promise<[string]>;

    HANDLER_ADMIN(overrides?: CallOverrides): Promise<[string]>;

    WITHDRAWER(overrides?: CallOverrides): Promise<[string]>;

    WITHDRAWER_ADMIN(overrides?: CallOverrides): Promise<[string]>;

    allowance(
      owner: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    approve(
      spender: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    asset(overrides?: CallOverrides): Promise<[string]>;

    authorizeReceiptInformation(
      account_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    authorizeReceiptTransfer(
      from_: PromiseOrValue<string>,
      to_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    balanceOf(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    balanceOfAt(
      account: PromiseOrValue<string>,
      snapshotId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    certify(
      until_: PromiseOrValue<BigNumberish>,
      data_: PromiseOrValue<BytesLike>,
      forceUntil_: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    confiscateReceipt(
      confiscatee_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    confiscateShares(
      confiscatee_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    convertToAssets(
      shares_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    convertToShares(
      assets_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    decimals(overrides?: CallOverrides): Promise<[number]>;

    decreaseAllowance(
      spender: PromiseOrValue<string>,
      subtractedValue: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "deposit(uint256,address,uint256,bytes)"(
      assets_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      depositMinShareRatio_: PromiseOrValue<BigNumberish>,
      receiptInformation_: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "deposit(uint256,address)"(
      assets_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    increaseAllowance(
      spender: PromiseOrValue<string>,
      addedValue: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    initialize(
      config_: OffchainAssetReceiptVaultConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    maxDeposit(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    maxMint(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "maxRedeem(address,uint256)"(
      owner_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "maxRedeem(address)"(
      owner_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "maxWithdraw(address,uint256)"(
      owner_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "maxWithdraw(address)"(
      owner_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    minShareRatios(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "mint(uint256,address)"(
      shares_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "mint(uint256,address,uint256,bytes)"(
      shares_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      mintMinShareRatio_: PromiseOrValue<BigNumberish>,
      receiptInformation_: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    multicall(
      data: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    name(overrides?: CallOverrides): Promise<[string]>;

    previewDeposit(
      assets_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    previewMint(
      shares_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "previewRedeem(uint256)"(
      shares_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "previewRedeem(uint256,uint256)"(
      shares_: PromiseOrValue<BigNumberish>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "previewWithdraw(uint256)"(
      assets_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "previewWithdraw(uint256,uint256)"(
      assets_: PromiseOrValue<BigNumberish>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "redeem(uint256,address,address,uint256)"(
      shares_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      owner_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "redeem(uint256,address,address)"(
      shares_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      owner_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    redeposit(
      assets_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      receiptInformation_: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setERC1155Tier(
      tier_: PromiseOrValue<string>,
      minimumTier_: PromiseOrValue<BigNumberish>,
      context_: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setERC20Tier(
      tier_: PromiseOrValue<string>,
      minimumTier_: PromiseOrValue<BigNumberish>,
      context_: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMinShareRatio(
      senderMinShareRatio_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setWithdrawId(
      id_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    snapshot(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    symbol(overrides?: CallOverrides): Promise<[string]>;

    totalAssets(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalSupplyAt(
      snapshotId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    transfer(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "withdraw(uint256,address,address,uint256)"(
      assets_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      owner_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "withdraw(uint256,address,address)"(
      assets_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      owner_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawIds(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  CERTIFIER(overrides?: CallOverrides): Promise<string>;

  CERTIFIER_ADMIN(overrides?: CallOverrides): Promise<string>;

  CONFISCATOR(overrides?: CallOverrides): Promise<string>;

  CONFISCATOR_ADMIN(overrides?: CallOverrides): Promise<string>;

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  DEPOSITOR(overrides?: CallOverrides): Promise<string>;

  DEPOSITOR_ADMIN(overrides?: CallOverrides): Promise<string>;

  ERC1155TIERER(overrides?: CallOverrides): Promise<string>;

  ERC1155TIERER_ADMIN(overrides?: CallOverrides): Promise<string>;

  ERC20SNAPSHOTTER(overrides?: CallOverrides): Promise<string>;

  ERC20SNAPSHOTTER_ADMIN(overrides?: CallOverrides): Promise<string>;

  ERC20TIERER(overrides?: CallOverrides): Promise<string>;

  ERC20TIERER_ADMIN(overrides?: CallOverrides): Promise<string>;

  HANDLER(overrides?: CallOverrides): Promise<string>;

  HANDLER_ADMIN(overrides?: CallOverrides): Promise<string>;

  WITHDRAWER(overrides?: CallOverrides): Promise<string>;

  WITHDRAWER_ADMIN(overrides?: CallOverrides): Promise<string>;

  allowance(
    owner: PromiseOrValue<string>,
    spender: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  approve(
    spender: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  asset(overrides?: CallOverrides): Promise<string>;

  authorizeReceiptInformation(
    account_: PromiseOrValue<string>,
    id_: PromiseOrValue<BigNumberish>,
    arg2: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<void>;

  authorizeReceiptTransfer(
    from_: PromiseOrValue<string>,
    to_: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<void>;

  balanceOf(
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  balanceOfAt(
    account: PromiseOrValue<string>,
    snapshotId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  certify(
    until_: PromiseOrValue<BigNumberish>,
    data_: PromiseOrValue<BytesLike>,
    forceUntil_: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  confiscateReceipt(
    confiscatee_: PromiseOrValue<string>,
    id_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  confiscateShares(
    confiscatee_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  convertToAssets(
    shares_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  convertToShares(
    assets_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  decimals(overrides?: CallOverrides): Promise<number>;

  decreaseAllowance(
    spender: PromiseOrValue<string>,
    subtractedValue: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "deposit(uint256,address,uint256,bytes)"(
    assets_: PromiseOrValue<BigNumberish>,
    receiver_: PromiseOrValue<string>,
    depositMinShareRatio_: PromiseOrValue<BigNumberish>,
    receiptInformation_: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "deposit(uint256,address)"(
    assets_: PromiseOrValue<BigNumberish>,
    receiver_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getRoleAdmin(
    role: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  grantRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  increaseAllowance(
    spender: PromiseOrValue<string>,
    addedValue: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  initialize(
    config_: OffchainAssetReceiptVaultConfigStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  maxDeposit(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  maxMint(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "maxRedeem(address,uint256)"(
    owner_: PromiseOrValue<string>,
    id_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "maxRedeem(address)"(
    owner_: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "maxWithdraw(address,uint256)"(
    owner_: PromiseOrValue<string>,
    id_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "maxWithdraw(address)"(
    owner_: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  minShareRatios(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "mint(uint256,address)"(
    shares_: PromiseOrValue<BigNumberish>,
    receiver_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "mint(uint256,address,uint256,bytes)"(
    shares_: PromiseOrValue<BigNumberish>,
    receiver_: PromiseOrValue<string>,
    mintMinShareRatio_: PromiseOrValue<BigNumberish>,
    receiptInformation_: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  multicall(
    data: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  name(overrides?: CallOverrides): Promise<string>;

  previewDeposit(
    assets_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  previewMint(
    shares_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "previewRedeem(uint256)"(
    shares_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "previewRedeem(uint256,uint256)"(
    shares_: PromiseOrValue<BigNumberish>,
    id_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "previewWithdraw(uint256)"(
    assets_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "previewWithdraw(uint256,uint256)"(
    assets_: PromiseOrValue<BigNumberish>,
    id_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "redeem(uint256,address,address,uint256)"(
    shares_: PromiseOrValue<BigNumberish>,
    receiver_: PromiseOrValue<string>,
    owner_: PromiseOrValue<string>,
    id_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "redeem(uint256,address,address)"(
    shares_: PromiseOrValue<BigNumberish>,
    receiver_: PromiseOrValue<string>,
    owner_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  redeposit(
    assets_: PromiseOrValue<BigNumberish>,
    receiver_: PromiseOrValue<string>,
    id_: PromiseOrValue<BigNumberish>,
    receiptInformation_: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setERC1155Tier(
    tier_: PromiseOrValue<string>,
    minimumTier_: PromiseOrValue<BigNumberish>,
    context_: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setERC20Tier(
    tier_: PromiseOrValue<string>,
    minimumTier_: PromiseOrValue<BigNumberish>,
    context_: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMinShareRatio(
    senderMinShareRatio_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setWithdrawId(
    id_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  snapshot(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  symbol(overrides?: CallOverrides): Promise<string>;

  totalAssets(overrides?: CallOverrides): Promise<BigNumber>;

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  totalSupplyAt(
    snapshotId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  transfer(
    to: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferFrom(
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "withdraw(uint256,address,address,uint256)"(
    assets_: PromiseOrValue<BigNumberish>,
    receiver_: PromiseOrValue<string>,
    owner_: PromiseOrValue<string>,
    id_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "withdraw(uint256,address,address)"(
    assets_: PromiseOrValue<BigNumberish>,
    receiver_: PromiseOrValue<string>,
    owner_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawIds(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    CERTIFIER(overrides?: CallOverrides): Promise<string>;

    CERTIFIER_ADMIN(overrides?: CallOverrides): Promise<string>;

    CONFISCATOR(overrides?: CallOverrides): Promise<string>;

    CONFISCATOR_ADMIN(overrides?: CallOverrides): Promise<string>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    DEPOSITOR(overrides?: CallOverrides): Promise<string>;

    DEPOSITOR_ADMIN(overrides?: CallOverrides): Promise<string>;

    ERC1155TIERER(overrides?: CallOverrides): Promise<string>;

    ERC1155TIERER_ADMIN(overrides?: CallOverrides): Promise<string>;

    ERC20SNAPSHOTTER(overrides?: CallOverrides): Promise<string>;

    ERC20SNAPSHOTTER_ADMIN(overrides?: CallOverrides): Promise<string>;

    ERC20TIERER(overrides?: CallOverrides): Promise<string>;

    ERC20TIERER_ADMIN(overrides?: CallOverrides): Promise<string>;

    HANDLER(overrides?: CallOverrides): Promise<string>;

    HANDLER_ADMIN(overrides?: CallOverrides): Promise<string>;

    WITHDRAWER(overrides?: CallOverrides): Promise<string>;

    WITHDRAWER_ADMIN(overrides?: CallOverrides): Promise<string>;

    allowance(
      owner: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    asset(overrides?: CallOverrides): Promise<string>;

    authorizeReceiptInformation(
      account_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    authorizeReceiptTransfer(
      from_: PromiseOrValue<string>,
      to_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    balanceOf(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOfAt(
      account: PromiseOrValue<string>,
      snapshotId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    certify(
      until_: PromiseOrValue<BigNumberish>,
      data_: PromiseOrValue<BytesLike>,
      forceUntil_: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    confiscateReceipt(
      confiscatee_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    confiscateShares(
      confiscatee_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertToAssets(
      shares_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertToShares(
      assets_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<number>;

    decreaseAllowance(
      spender: PromiseOrValue<string>,
      subtractedValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "deposit(uint256,address,uint256,bytes)"(
      assets_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      depositMinShareRatio_: PromiseOrValue<BigNumberish>,
      receiptInformation_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "deposit(uint256,address)"(
      assets_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    increaseAllowance(
      spender: PromiseOrValue<string>,
      addedValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    initialize(
      config_: OffchainAssetReceiptVaultConfigStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    maxDeposit(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxMint(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "maxRedeem(address,uint256)"(
      owner_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "maxRedeem(address)"(
      owner_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "maxWithdraw(address,uint256)"(
      owner_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "maxWithdraw(address)"(
      owner_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    minShareRatios(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "mint(uint256,address)"(
      shares_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "mint(uint256,address,uint256,bytes)"(
      shares_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      mintMinShareRatio_: PromiseOrValue<BigNumberish>,
      receiptInformation_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    multicall(
      data: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<string[]>;

    name(overrides?: CallOverrides): Promise<string>;

    previewDeposit(
      assets_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    previewMint(
      shares_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "previewRedeem(uint256)"(
      shares_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "previewRedeem(uint256,uint256)"(
      shares_: PromiseOrValue<BigNumberish>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "previewWithdraw(uint256)"(
      assets_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "previewWithdraw(uint256,uint256)"(
      assets_: PromiseOrValue<BigNumberish>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "redeem(uint256,address,address,uint256)"(
      shares_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      owner_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "redeem(uint256,address,address)"(
      shares_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      owner_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    redeposit(
      assets_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      receiptInformation_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setERC1155Tier(
      tier_: PromiseOrValue<string>,
      minimumTier_: PromiseOrValue<BigNumberish>,
      context_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    setERC20Tier(
      tier_: PromiseOrValue<string>,
      minimumTier_: PromiseOrValue<BigNumberish>,
      context_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    setMinShareRatio(
      senderMinShareRatio_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setWithdrawId(
      id_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    snapshot(overrides?: CallOverrides): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    symbol(overrides?: CallOverrides): Promise<string>;

    totalAssets(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupplyAt(
      snapshotId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transfer(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "withdraw(uint256,address,address,uint256)"(
      assets_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      owner_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "withdraw(uint256,address,address)"(
      assets_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      owner_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawIds(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "Approval(address,address,uint256)"(
      owner?: PromiseOrValue<string> | null,
      spender?: PromiseOrValue<string> | null,
      value?: null
    ): ApprovalEventFilter;
    Approval(
      owner?: PromiseOrValue<string> | null,
      spender?: PromiseOrValue<string> | null,
      value?: null
    ): ApprovalEventFilter;

    "Certify(address,uint256,bytes)"(
      caller?: null,
      until?: null,
      data?: null
    ): CertifyEventFilter;
    Certify(caller?: null, until?: null, data?: null): CertifyEventFilter;

    "ConfiscateReceipt(address,address,uint256,uint256)"(
      caller?: null,
      confiscatee?: null,
      id?: null,
      confiscated?: null
    ): ConfiscateReceiptEventFilter;
    ConfiscateReceipt(
      caller?: null,
      confiscatee?: null,
      id?: null,
      confiscated?: null
    ): ConfiscateReceiptEventFilter;

    "ConfiscateShares(address,address,uint256)"(
      caller?: null,
      confiscatee?: null,
      confiscated?: null
    ): ConfiscateSharesEventFilter;
    ConfiscateShares(
      caller?: null,
      confiscatee?: null,
      confiscated?: null
    ): ConfiscateSharesEventFilter;

    "Deposit(address,address,uint256,uint256)"(
      sender?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null,
      assets?: null,
      shares?: null
    ): DepositEventFilter;
    Deposit(
      sender?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null,
      assets?: null,
      shares?: null
    ): DepositEventFilter;

    "DepositWithReceipt(address,address,uint256,uint256,uint256,bytes)"(
      sender?: null,
      owner?: null,
      assets?: null,
      shares?: null,
      id?: null,
      receiptInformation?: null
    ): DepositWithReceiptEventFilter;
    DepositWithReceipt(
      sender?: null,
      owner?: null,
      assets?: null,
      shares?: null,
      id?: null,
      receiptInformation?: null
    ): DepositWithReceiptEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "OffchainAssetVaultInitialized(address,tuple)"(
      caller?: null,
      config?: null
    ): OffchainAssetVaultInitializedEventFilter;
    OffchainAssetVaultInitialized(
      caller?: null,
      config?: null
    ): OffchainAssetVaultInitializedEventFilter;

    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;
    RoleAdminChanged(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;

    "RoleGranted(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;
    RoleGranted(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;

    "RoleRevoked(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;
    RoleRevoked(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;

    "SetERC1155Tier(address,address,uint256,uint256[])"(
      caller?: null,
      tier?: null,
      minimumTier?: null,
      context?: null
    ): SetERC1155TierEventFilter;
    SetERC1155Tier(
      caller?: null,
      tier?: null,
      minimumTier?: null,
      context?: null
    ): SetERC1155TierEventFilter;

    "SetERC20Tier(address,address,uint256,uint256[])"(
      caller?: null,
      tier?: null,
      minimumTier?: null,
      context?: null
    ): SetERC20TierEventFilter;
    SetERC20Tier(
      caller?: null,
      tier?: null,
      minimumTier?: null,
      context?: null
    ): SetERC20TierEventFilter;

    "Snapshot(uint256)"(id?: null): SnapshotEventFilter;
    Snapshot(id?: null): SnapshotEventFilter;

    "Transfer(address,address,uint256)"(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      value?: null
    ): TransferEventFilter;
    Transfer(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      value?: null
    ): TransferEventFilter;

    "Withdraw(address,address,address,uint256,uint256)"(
      sender?: PromiseOrValue<string> | null,
      receiver?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null,
      assets?: null,
      shares?: null
    ): WithdrawEventFilter;
    Withdraw(
      sender?: PromiseOrValue<string> | null,
      receiver?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null,
      assets?: null,
      shares?: null
    ): WithdrawEventFilter;

    "WithdrawWithReceipt(address,address,address,uint256,uint256,uint256)"(
      sender?: null,
      receiver?: null,
      owner?: null,
      assets?: null,
      shares?: null,
      id?: null
    ): WithdrawWithReceiptEventFilter;
    WithdrawWithReceipt(
      sender?: null,
      receiver?: null,
      owner?: null,
      assets?: null,
      shares?: null,
      id?: null
    ): WithdrawWithReceiptEventFilter;
  };

  estimateGas: {
    CERTIFIER(overrides?: CallOverrides): Promise<BigNumber>;

    CERTIFIER_ADMIN(overrides?: CallOverrides): Promise<BigNumber>;

    CONFISCATOR(overrides?: CallOverrides): Promise<BigNumber>;

    CONFISCATOR_ADMIN(overrides?: CallOverrides): Promise<BigNumber>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    DEPOSITOR(overrides?: CallOverrides): Promise<BigNumber>;

    DEPOSITOR_ADMIN(overrides?: CallOverrides): Promise<BigNumber>;

    ERC1155TIERER(overrides?: CallOverrides): Promise<BigNumber>;

    ERC1155TIERER_ADMIN(overrides?: CallOverrides): Promise<BigNumber>;

    ERC20SNAPSHOTTER(overrides?: CallOverrides): Promise<BigNumber>;

    ERC20SNAPSHOTTER_ADMIN(overrides?: CallOverrides): Promise<BigNumber>;

    ERC20TIERER(overrides?: CallOverrides): Promise<BigNumber>;

    ERC20TIERER_ADMIN(overrides?: CallOverrides): Promise<BigNumber>;

    HANDLER(overrides?: CallOverrides): Promise<BigNumber>;

    HANDLER_ADMIN(overrides?: CallOverrides): Promise<BigNumber>;

    WITHDRAWER(overrides?: CallOverrides): Promise<BigNumber>;

    WITHDRAWER_ADMIN(overrides?: CallOverrides): Promise<BigNumber>;

    allowance(
      owner: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    asset(overrides?: CallOverrides): Promise<BigNumber>;

    authorizeReceiptInformation(
      account_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    authorizeReceiptTransfer(
      from_: PromiseOrValue<string>,
      to_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOf(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOfAt(
      account: PromiseOrValue<string>,
      snapshotId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    certify(
      until_: PromiseOrValue<BigNumberish>,
      data_: PromiseOrValue<BytesLike>,
      forceUntil_: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    confiscateReceipt(
      confiscatee_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    confiscateShares(
      confiscatee_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    convertToAssets(
      shares_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertToShares(
      assets_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<BigNumber>;

    decreaseAllowance(
      spender: PromiseOrValue<string>,
      subtractedValue: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "deposit(uint256,address,uint256,bytes)"(
      assets_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      depositMinShareRatio_: PromiseOrValue<BigNumberish>,
      receiptInformation_: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "deposit(uint256,address)"(
      assets_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    increaseAllowance(
      spender: PromiseOrValue<string>,
      addedValue: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    initialize(
      config_: OffchainAssetReceiptVaultConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    maxDeposit(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxMint(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "maxRedeem(address,uint256)"(
      owner_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "maxRedeem(address)"(
      owner_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "maxWithdraw(address,uint256)"(
      owner_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "maxWithdraw(address)"(
      owner_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    minShareRatios(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "mint(uint256,address)"(
      shares_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "mint(uint256,address,uint256,bytes)"(
      shares_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      mintMinShareRatio_: PromiseOrValue<BigNumberish>,
      receiptInformation_: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    multicall(
      data: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    previewDeposit(
      assets_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    previewMint(
      shares_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "previewRedeem(uint256)"(
      shares_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "previewRedeem(uint256,uint256)"(
      shares_: PromiseOrValue<BigNumberish>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "previewWithdraw(uint256)"(
      assets_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "previewWithdraw(uint256,uint256)"(
      assets_: PromiseOrValue<BigNumberish>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "redeem(uint256,address,address,uint256)"(
      shares_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      owner_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "redeem(uint256,address,address)"(
      shares_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      owner_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    redeposit(
      assets_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      receiptInformation_: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setERC1155Tier(
      tier_: PromiseOrValue<string>,
      minimumTier_: PromiseOrValue<BigNumberish>,
      context_: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setERC20Tier(
      tier_: PromiseOrValue<string>,
      minimumTier_: PromiseOrValue<BigNumberish>,
      context_: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMinShareRatio(
      senderMinShareRatio_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setWithdrawId(
      id_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    snapshot(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;

    totalAssets(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupplyAt(
      snapshotId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transfer(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "withdraw(uint256,address,address,uint256)"(
      assets_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      owner_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "withdraw(uint256,address,address)"(
      assets_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      owner_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawIds(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    CERTIFIER(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    CERTIFIER_ADMIN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    CONFISCATOR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    CONFISCATOR_ADMIN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    DEPOSITOR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DEPOSITOR_ADMIN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ERC1155TIERER(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ERC1155TIERER_ADMIN(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ERC20SNAPSHOTTER(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ERC20SNAPSHOTTER_ADMIN(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ERC20TIERER(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ERC20TIERER_ADMIN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    HANDLER(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    HANDLER_ADMIN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    WITHDRAWER(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    WITHDRAWER_ADMIN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    allowance(
      owner: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    approve(
      spender: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    asset(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    authorizeReceiptInformation(
      account_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    authorizeReceiptTransfer(
      from_: PromiseOrValue<string>,
      to_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    balanceOf(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    balanceOfAt(
      account: PromiseOrValue<string>,
      snapshotId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    certify(
      until_: PromiseOrValue<BigNumberish>,
      data_: PromiseOrValue<BytesLike>,
      forceUntil_: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    confiscateReceipt(
      confiscatee_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    confiscateShares(
      confiscatee_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    convertToAssets(
      shares_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertToShares(
      assets_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    decimals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    decreaseAllowance(
      spender: PromiseOrValue<string>,
      subtractedValue: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "deposit(uint256,address,uint256,bytes)"(
      assets_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      depositMinShareRatio_: PromiseOrValue<BigNumberish>,
      receiptInformation_: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "deposit(uint256,address)"(
      assets_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    increaseAllowance(
      spender: PromiseOrValue<string>,
      addedValue: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      config_: OffchainAssetReceiptVaultConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    maxDeposit(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxMint(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "maxRedeem(address,uint256)"(
      owner_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "maxRedeem(address)"(
      owner_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "maxWithdraw(address,uint256)"(
      owner_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "maxWithdraw(address)"(
      owner_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minShareRatios(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "mint(uint256,address)"(
      shares_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "mint(uint256,address,uint256,bytes)"(
      shares_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      mintMinShareRatio_: PromiseOrValue<BigNumberish>,
      receiptInformation_: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    multicall(
      data: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    previewDeposit(
      assets_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    previewMint(
      shares_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "previewRedeem(uint256)"(
      shares_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "previewRedeem(uint256,uint256)"(
      shares_: PromiseOrValue<BigNumberish>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "previewWithdraw(uint256)"(
      assets_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "previewWithdraw(uint256,uint256)"(
      assets_: PromiseOrValue<BigNumberish>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "redeem(uint256,address,address,uint256)"(
      shares_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      owner_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "redeem(uint256,address,address)"(
      shares_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      owner_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    redeposit(
      assets_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      receiptInformation_: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setERC1155Tier(
      tier_: PromiseOrValue<string>,
      minimumTier_: PromiseOrValue<BigNumberish>,
      context_: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setERC20Tier(
      tier_: PromiseOrValue<string>,
      minimumTier_: PromiseOrValue<BigNumberish>,
      context_: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMinShareRatio(
      senderMinShareRatio_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setWithdrawId(
      id_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    snapshot(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalAssets(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalSupplyAt(
      snapshotId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transfer(
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "withdraw(uint256,address,address,uint256)"(
      assets_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      owner_: PromiseOrValue<string>,
      id_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "withdraw(uint256,address,address)"(
      assets_: PromiseOrValue<BigNumberish>,
      receiver_: PromiseOrValue<string>,
      owner_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawIds(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
