/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { OffchainAssetReceiptVault__factory } from "./OffchainAssetReceiptVault__factory";
export { OffchainAssetReceiptVaultFactory__factory } from "./OffchainAssetReceiptVaultFactory__factory";
